USE ROLE ANALYST;
USE WAREHOUSE AD_HOC_WH;

-- LETS SEE IF NAME IS MASKED
SELECT NAME, *
FROM RAW.SUPERHERO.HEROES_INFORMATION
LIMIT 20;

SELECT NAME, *
FROM RAW.SUPERHERO.SUPERHERO_DB
LIMIT 20;

-- HASH IS DETERMINISTIC  - THE SAME STRING WILL ALWAYS HAVE THE SAME HASH VALUE. CAN DO SOME ANALYTICS WITHOUT NEEDING TO KNOW THE ACTUAL PII
SELECT NAME ,*
FROM RAW.SUPERHERO.SUPERHERO_DB
QUALIFY COUNT(*) OVER (PARTITION BY NAME) >1;

USE ROLE ANALYST_BII;
USE WAREHOUSE AD_HOC_WH;

-- CLEAR TEXT
SELECT NAME, *
FROM RAW.SUPERHERO.HEROES_INFORMATION
LIMIT 20;

SELECT NAME, *
FROM RAW.SUPERHERO.SUPERHERO_DB
LIMIT 20;
