
use role sysadmin;
use database data_vault;
use schema staging;

-- original DV - URL is the business key
-- but URL contains BII - superhero name so cannot use it.
select JSON_RAW:urls.wikipedia :: string as SOURCE_URL,
* 
from RAW.SUPERHERO.SUPERHEROES_MARVEL_SEARCH;

-- create synthetic autoincremeted number

create or replace table RAW.SUPERHERO.SUPERHEROES_MARVEL_SEARCH_WITH_ID LIKE RAW.SUPERHERO.SUPERHEROES_MARVEL_SEARCH;
alter table RAW.SUPERHERO.SUPERHEROES_MARVEL_SEARCH_WITH_ID add column id int identity(1,1) not null;


insert into RAW.SUPERHERO.SUPERHEROES_MARVEL_SEARCH_WITH_ID (JSON_RAW)
select JSON_RAW
from RAW.SUPERHERO.SUPERHEROES_MARVEL_SEARCH;


SELECT * FROM RAW.SUPERHERO.SUPERHEROES_MARVEL_SEARCH_WITH_ID;

create or replace view STG_SUPERHEROES_MARVEL_SEARCH
as
SELECT 
ID as BEING_ID,
'https://github.com/algolia/marvel-search:' || ID::STRING AS BEING_ID_BKCC,
MD5(BEING_ID_BKCC) AS HUB_BEING_KEY,
parse_json(
    '{"Source_System": "https://github.com/algolia/marvel-search", 
    "Source_Table": "RAW.SUPERHERO.SUPERHEROES_MARVEL_SEARCH", 
     "Source_Columns": { "SOURCE_URL": ["JSON_RAW:urls.wikipedia"] } 
      }' ) :: variant AS RECORD_SOURCE,
current_timestamp()::timestamp_tz as LOAD_DATE, -- in UTC
MD5(BEING_ID_BKCC ||  LOAD_DATE) as SAT_BEING_MARVEL_SEARCH_KEY,
JSON_RAW,
MD5(JSON_RAW) AS RECORD_HASH
from RAW.SUPERHERO.SUPERHEROES_MARVEL_SEARCH_WITH_ID;



SELECT * FROM STG_SUPERHEROES_MARVEL_SEARCH;



INSERT INTO superhero.HUB_BEING
SELECT 
    DISTINCT 
    HUB_BEING_KEY,
    BEING_ID,
    BEING_ID_BKCC,
    RECORD_SOURCE,
    LOAD_DATE     
FROM DATA_VAULT.STAGING.STG_SUPERHEROES_MARVEL_SEARCH STG
 WHERE NOT EXISTS (SELECT * FROM DATA_VAULT.SUPERHERO.HUB_BEING HB WHERE STG.HUB_BEING_KEY = HB.HUB_BEING_KEY );


INSERT INTO superhero.SAT_BEING_MARVEL_SEARCH_BII
SELECT 
    SAT_BEING_MARVEL_SEARCH_KEY,
    HUB_BEING_KEY,
    BEING_ID,
    BEING_ID_BKCC,
    JSON_RAW,
    RECORD_HASH,
    LOAD_DATE     
FROM DATA_VAULT.STAGING.STG_SUPERHEROES_MARVEL_SEARCH STG
 WHERE NOT EXISTS (SELECT * FROM DATA_VAULT.SUPERHERO.SAT_BEING_MARVEL_SEARCH_BII SB WHERE STG.HUB_BEING_KEY = SB.HUB_BEING_KEY 
                  and STG.RECORD_HASH = SB.RECORD_HASH);



SELECT *
FROM DATA_VAULT.SUPERHERO.HUB_BEING;

SELECT *
FROM DATA_VAULT.SUPERHERO.SAT_BEING_MARVEL_SEARCH_BII;