
use role sysadmin;
use database data_vault;
use schema staging;


-- create staging view
use role sysadmin;
use database data_vault;
use schema staging;

create or replace view STG_SUPERHERO_SET
as
select 
HI.HERO_ID AS BEING_ID
,'www.kaggle.com/claudiodavi/superhero-set:' || HI.HERO_ID::STRING AS BEING_ID_BKCC
,MD5(BEING_ID_BKCC) AS HUB_BEING_KEY
,parse_json(
        '{"Source_System": "https://www.kaggle.com/claudiodavi/superhero-set", 
        "Source_Table": "RAW.SUPERHERO.HEROES_INFORMATION", 
        "Source_Columns": { "BEING_ID": ["HERO_ID"] } 
         }'
            ) :: variant AS RECORD_SOURCE
,current_timestamp()::timestamp_tz as LOAD_DATE -- in UTC
,MD5(BEING_ID_BKCC ||  LOAD_DATE) as SAT_BEING_SUPERHERO_SET_KEY
,HI.NAME
,HI.GENDER
,HI.EYE_COLOR
,HI.RACE
,HI.HAIR_COLOR
,HI.HEIGHT::NUMERIC(9,4) AS HEIGHT
,HI.WEIGHT::NUMERIC(9,4) AS WEIGHT
,HI.SKIN_COLOR
,HI.PUBLISHER 
,HI.ALIGNMENT
,SP.AGILITY::BOOLEAN AS AGILITY
,SP.ACCELERATED_HEALING::BOOLEAN AS ACCELERATED_HEALING
,SP.LANTERN_POWER_RING::BOOLEAN AS LANTERN_POWER_RING
,SP.DIMENSIONAL_AWARENESS::BOOLEAN AS DIMENSIONAL_AWARENESS
,SP.COLD_RESISTANCE::BOOLEAN AS COLD_RESISTANCE
,SP.DURABILITY::BOOLEAN AS DURABILITY
,SP.STEALTH::BOOLEAN AS STEALTH
,SP.ENERGY_ABSORPTION::BOOLEAN AS ENERGY_ABSORPTION
,SP.FLIGHT::BOOLEAN AS FLIGHT
,SP.DANGER_SENSE::BOOLEAN AS DANGER_SENSE
,SP.UNDERWATER_BREATHING::BOOLEAN AS UNDERWATER_BREATHING
,SP.MARKSMANSHIP::BOOLEAN AS MARKSMANSHIP
,SP.WEAPONS_MASTER::BOOLEAN AS WEAPONS_MASTER
,SP.POWER_AUGMENTATION::BOOLEAN AS POWER_AUGMENTATION
,SP.ANIMAL_ATTRIBUTES::BOOLEAN AS ANIMAL_ATTRIBUTES
,SP.LONGEVITY::BOOLEAN AS LONGEVITY
,SP.INTELLIGENCE::BOOLEAN AS INTELLIGENCE
,SP.SUPER_STRENGTH::BOOLEAN AS SUPER_STRENGTH
,SP.CRYOKINESIS::BOOLEAN AS CRYOKINESIS
,SP.TELEPATHY::BOOLEAN AS TELEPATHY
,SP.ENERGY_ARMOR::BOOLEAN AS ENERGY_ARMOR
,SP.ENERGY_BLASTS::BOOLEAN AS ENERGY_BLASTS
,SP.DUPLICATION::BOOLEAN AS DUPLICATION
,SP.SIZE_CHANGING::BOOLEAN AS SIZE_CHANGING
,SP.DENSITY_CONTROL::BOOLEAN AS DENSITY_CONTROL
,SP.STAMINA::BOOLEAN AS STAMINA
,SP.ASTRAL_TRAVEL::BOOLEAN AS ASTRAL_TRAVEL
,SP.AUDIO_CONTROL::BOOLEAN AS AUDIO_CONTROL
,SP.DEXTERITY::BOOLEAN AS DEXTERITY
,SP.OMNITRIX::BOOLEAN AS OMNITRIX
,SP.SUPER_SPEED::BOOLEAN AS SUPER_SPEED
,SP.POSSESSION::BOOLEAN AS POSSESSION
,SP.ANIMAL_ORIENTED_POWERS::BOOLEAN AS ANIMAL_ORIENTED_POWERS
,SP.WEAPON_BASED_POWERS::BOOLEAN AS WEAPON_BASED_POWERS
,SP.ELECTROKINESIS::BOOLEAN AS ELECTROKINESIS
,SP.DARKFORCE_MANIPULATION::BOOLEAN AS DARKFORCE_MANIPULATION
,SP.DEATH_TOUCH::BOOLEAN AS DEATH_TOUCH
,SP.TELEPORTATION::BOOLEAN AS TELEPORTATION
,SP.ENHANCED_SENSES::BOOLEAN AS ENHANCED_SENSES
,SP.TELEKINESIS::BOOLEAN AS TELEKINESIS
,SP.ENERGY_BEAMS::BOOLEAN AS ENERGY_BEAMS
,SP.MAGIC::BOOLEAN AS MAGIC
,SP.HYPERKINESIS::BOOLEAN AS HYPERKINESIS
,SP.JUMP::BOOLEAN AS JUMP
,SP.CLAIRVOYANCE::BOOLEAN AS CLAIRVOYANCE
,SP.DIMENSIONAL_TRAVEL::BOOLEAN AS DIMENSIONAL_TRAVEL
,SP.POWER_SENSE::BOOLEAN AS POWER_SENSE
,SP.SHAPESHIFTING::BOOLEAN AS SHAPESHIFTING
,SP.PEAK_HUMAN_CONDITION::BOOLEAN AS PEAK_HUMAN_CONDITION
,SP.IMMORTALITY::BOOLEAN AS IMMORTALITY
,SP.CAMOUFLAGE::BOOLEAN AS CAMOUFLAGE
,SP.ELEMENT_CONTROL::BOOLEAN AS ELEMENT_CONTROL
,SP.PHASING::BOOLEAN AS PHASING
,SP.ASTRAL_PROJECTION::BOOLEAN AS ASTRAL_PROJECTION
,SP.ELECTRICAL_TRANSPORT::BOOLEAN AS ELECTRICAL_TRANSPORT
,SP.FIRE_CONTROL::BOOLEAN AS FIRE_CONTROL
,SP.PROJECTION::BOOLEAN AS PROJECTION
,SP.SUMMONING::BOOLEAN AS SUMMONING
,SP.ENHANCED_MEMORY::BOOLEAN AS ENHANCED_MEMORY
,SP.REFLEXES::BOOLEAN AS REFLEXES
,SP.INVULNERABILITY::BOOLEAN AS INVULNERABILITY
,SP.ENERGY_CONSTRUCTS::BOOLEAN AS ENERGY_CONSTRUCTS
,SP.FORCE_FIELDS::BOOLEAN AS FORCE_FIELDS
,SP.SELF_SUSTENANCE::BOOLEAN AS SELF_SUSTENANCE
,SP.ANTI_GRAVITY::BOOLEAN AS ANTI_GRAVITY
,SP.EMPATHY::BOOLEAN AS EMPATHY
,SP.POWER_NULLIFIER::BOOLEAN AS POWER_NULLIFIER
,SP.RADIATION_CONTROL::BOOLEAN AS RADIATION_CONTROL
,SP.PSIONIC_POWERS::BOOLEAN AS PSIONIC_POWERS
,SP.ELASTICITY::BOOLEAN AS ELASTICITY
,SP.SUBSTANCE_SECRETION::BOOLEAN AS SUBSTANCE_SECRETION
,SP.ELEMENTAL_TRANSMOGRIFICATION::BOOLEAN AS ELEMENTAL_TRANSMOGRIFICATION
,SP.TECHNOPATH_CYBERPATH::BOOLEAN AS TECHNOPATH_CYBERPATH
,SP.PHOTOGRAPHIC_REFLEXES::BOOLEAN AS PHOTOGRAPHIC_REFLEXES
,SP.SEISMIC_POWER::BOOLEAN AS SEISMIC_POWER
,SP.ANIMATION::BOOLEAN AS ANIMATION
,SP.PRECOGNITION::BOOLEAN AS PRECOGNITION
,SP.MIND_CONTROL::BOOLEAN AS MIND_CONTROL
,SP.FIRE_RESISTANCE::BOOLEAN AS FIRE_RESISTANCE
,SP.POWER_ABSORPTION::BOOLEAN AS POWER_ABSORPTION
,SP.ENHANCED_HEARING::BOOLEAN AS ENHANCED_HEARING
,SP.NOVA_FORCE::BOOLEAN AS NOVA_FORCE
,SP.INSANITY::BOOLEAN AS INSANITY
,SP.HYPNOKINESIS::BOOLEAN AS HYPNOKINESIS
,SP.ANIMAL_CONTROL::BOOLEAN AS ANIMAL_CONTROL
,SP.NATURAL_ARMOR::BOOLEAN AS NATURAL_ARMOR
,SP.INTANGIBILITY::BOOLEAN AS INTANGIBILITY
,SP.ENHANCED_SIGHT::BOOLEAN AS ENHANCED_SIGHT
,SP.MOLECULAR_MANIPULATION::BOOLEAN AS MOLECULAR_MANIPULATION
,SP.HEAT_GENERATION::BOOLEAN AS HEAT_GENERATION
,SP.ADAPTATION::BOOLEAN AS ADAPTATION
,SP.GLIDING::BOOLEAN AS GLIDING
,SP.POWER_SUIT::BOOLEAN AS POWER_SUIT
,SP.MIND_BLAST::BOOLEAN AS MIND_BLAST
,SP.PROBABILITY_MANIPULATION::BOOLEAN AS PROBABILITY_MANIPULATION
,SP.GRAVITY_CONTROL::BOOLEAN AS GRAVITY_CONTROL
,SP.REGENERATION::BOOLEAN AS REGENERATION
,SP.LIGHT_CONTROL::BOOLEAN AS LIGHT_CONTROL
,SP.ECHOLOCATION::BOOLEAN AS ECHOLOCATION
,SP.LEVITATION::BOOLEAN AS LEVITATION
,SP.TOXIN_AND_DISEASE_CONTROL::BOOLEAN AS TOXIN_AND_DISEASE_CONTROL
,SP.BANISH::BOOLEAN AS BANISH
,SP.ENERGY_MANIPULATION::BOOLEAN AS ENERGY_MANIPULATION
,SP.HEAT_RESISTANCE::BOOLEAN AS HEAT_RESISTANCE
,SP.NATURAL_WEAPONS::BOOLEAN AS NATURAL_WEAPONS
,SP.TIME_TRAVEL::BOOLEAN AS TIME_TRAVEL
,SP.ENHANCED_SMELL::BOOLEAN AS ENHANCED_SMELL
,SP.ILLUSIONS::BOOLEAN AS ILLUSIONS
,SP.THIRSTOKINESIS::BOOLEAN AS THIRSTOKINESIS
,SP.HAIR_MANIPULATION::BOOLEAN AS HAIR_MANIPULATION
,SP.ILLUMINATION::BOOLEAN AS ILLUMINATION
,SP.OMNIPOTENT::BOOLEAN AS OMNIPOTENT
,SP.CLOAKING::BOOLEAN AS CLOAKING
,SP.CHANGING_ARMOR::BOOLEAN AS CHANGING_ARMOR
,SP.POWER_COSMIC::BOOLEAN AS POWER_COSMIC
,SP.BIOKINESIS::BOOLEAN AS BIOKINESIS
,SP.WATER_CONTROL::BOOLEAN AS WATER_CONTROL
,SP.RADIATION_IMMUNITY::BOOLEAN AS RADIATION_IMMUNITY
,SP.VISION_TELESCOPIC::BOOLEAN AS VISION_TELESCOPIC
,SP.TOXIN_AND_DISEASE_RESISTANCE::BOOLEAN AS TOXIN_AND_DISEASE_RESISTANCE
,SP.SPATIAL_AWARENESS::BOOLEAN AS SPATIAL_AWARENESS
,SP.ENERGY_RESISTANCE::BOOLEAN AS ENERGY_RESISTANCE
,SP.TELEPATHY_RESISTANCE::BOOLEAN AS TELEPATHY_RESISTANCE
,SP.MOLECULAR_COMBUSTION::BOOLEAN AS MOLECULAR_COMBUSTION
,SP.OMNILINGUALISM::BOOLEAN AS OMNILINGUALISM
,SP.PORTAL_CREATION::BOOLEAN AS PORTAL_CREATION
,SP.MAGNETISM::BOOLEAN AS MAGNETISM
,SP.MIND_CONTROL_RESISTANCE::BOOLEAN AS MIND_CONTROL_RESISTANCE
,SP.PLANT_CONTROL::BOOLEAN AS PLANT_CONTROL
,SP.SONAR::BOOLEAN AS SONAR
,SP.SONIC_SCREAM::BOOLEAN AS SONIC_SCREAM
,SP.TIME_MANIPULATION::BOOLEAN AS TIME_MANIPULATION
,SP.ENHANCED_TOUCH::BOOLEAN AS ENHANCED_TOUCH
,SP.MAGIC_RESISTANCE::BOOLEAN AS MAGIC_RESISTANCE
,SP.INVISIBILITY::BOOLEAN AS INVISIBILITY
,SP.SUB_MARINER::BOOLEAN AS SUB_MARINER
,SP.RADIATION_ABSORPTION::BOOLEAN AS RADIATION_ABSORPTION
,SP.INTUITIVE_APTITUDE::BOOLEAN AS INTUITIVE_APTITUDE
,SP.VISION_MICROSCOPIC::BOOLEAN AS VISION_MICROSCOPIC
,SP.MELTING::BOOLEAN AS MELTING
,SP.WIND_CONTROL::BOOLEAN AS WIND_CONTROL
,SP.SUPER_BREATH::BOOLEAN  AS SUPER_BREATH
,SP.WALLCRAWLING::BOOLEAN AS WALLCRAWLING
,SP.VISION_NIGHT::BOOLEAN AS VISION_NIGHT
,SP.VISION_INFRARED::BOOLEAN AS VISION_INFRARED
,SP.GRIM_REAPING::BOOLEAN AS GRIM_REAPING
,SP.MATTER_ABSORPTION::BOOLEAN AS MATTER_ABSORPTION
,SP.THE_FORCE::BOOLEAN AS THE_FORCE
,SP.RESURRECTION::BOOLEAN AS RESURRECTION
,SP.TERRAKINESIS::BOOLEAN AS TERRAKINESIS
,SP.VISION_HEAT::BOOLEAN AS VISION_HEAT
,SP.VITAKINESIS::BOOLEAN AS VITAKINESIS
,SP.RADAR_SENSE::BOOLEAN AS RADAR_SENSE
,SP.QWARDIAN_POWER_RING::BOOLEAN AS QWARDIAN_POWER_RING
,SP.WEATHER_CONTROL::BOOLEAN AS WEATHER_CONTROL
,SP.VISION_XRAY::BOOLEAN AS VISION_XRAY
,SP.VISION_THERMAL::BOOLEAN AS VISION_THERMAL
,SP.WEB_CREATION::BOOLEAN AS WEB_CREATION
,SP.REALITY_WARPING::BOOLEAN AS REALITY_WARPING
,SP.ODIN_FORCE::BOOLEAN AS ODIN_FORCE
,SP.SYMBIOTE_COSTUME::BOOLEAN AS SYMBIOTE_COSTUME
,SP.SPEED_FORCE::BOOLEAN AS SPEED_FORCE
,SP.PHOENIX_FORCE::BOOLEAN AS PHOENIX_FORCE
,SP.MOLECULAR_DISSIPATION::BOOLEAN AS MOLECULAR_DISSIPATION
,SP.VISION_CRYO::BOOLEAN AS VISION_CRYO
,SP.OMNIPRESENT::BOOLEAN AS OMNIPRESENT
,SP.OMNISCIENT::BOOLEAN AS OMNISCIENT
,MD5(ARRAY_TO_STRING(ARRAY_CONSTRUCT(
    UPPER(TRIM(IFNULL(HI.PUBLISHER ,'')))
    ,UPPER(TRIM(IFNULL(HI.ALIGNMENT,'')))
    ,UPPER(TRIM(IFNULL(SP.AGILITY,'')))
    ,UPPER(TRIM(IFNULL(SP.ACCELERATED_HEALING,'')))
    ,UPPER(TRIM(IFNULL(SP.LANTERN_POWER_RING,'')))
    ,UPPER(TRIM(IFNULL(SP.DIMENSIONAL_AWARENESS,'')))
    ,UPPER(TRIM(IFNULL(SP.COLD_RESISTANCE,'')))
    ,UPPER(TRIM(IFNULL(SP.DURABILITY,'')))
    ,UPPER(TRIM(IFNULL(SP.STEALTH,'')))
    ,UPPER(TRIM(IFNULL(SP.ENERGY_ABSORPTION,'')))
    ,UPPER(TRIM(IFNULL(SP.FLIGHT,'')))
    ,UPPER(TRIM(IFNULL(SP.DANGER_SENSE,'')))
    ,UPPER(TRIM(IFNULL(SP.UNDERWATER_BREATHING,'')))
    ,UPPER(TRIM(IFNULL(SP.MARKSMANSHIP,'')))
    ,UPPER(TRIM(IFNULL(SP.WEAPONS_MASTER,'')))
    ,UPPER(TRIM(IFNULL(SP.POWER_AUGMENTATION,'')))
    ,UPPER(TRIM(IFNULL(SP.ANIMAL_ATTRIBUTES,'')))
    ,UPPER(TRIM(IFNULL(SP.LONGEVITY,'')))
    ,UPPER(TRIM(IFNULL(SP.INTELLIGENCE,'')))
    ,UPPER(TRIM(IFNULL(SP.SUPER_STRENGTH,'')))
    ,UPPER(TRIM(IFNULL(SP.CRYOKINESIS,'')))
    ,UPPER(TRIM(IFNULL(SP.TELEPATHY,'')))
    ,UPPER(TRIM(IFNULL(SP.ENERGY_ARMOR,'')))
    ,UPPER(TRIM(IFNULL(SP.ENERGY_BLASTS,'')))
    ,UPPER(TRIM(IFNULL(SP.DUPLICATION,'')))
    ,UPPER(TRIM(IFNULL(SP.SIZE_CHANGING,'')))
    ,UPPER(TRIM(IFNULL(SP.DENSITY_CONTROL,'')))
    ,UPPER(TRIM(IFNULL(SP.STAMINA,'')))
    ,UPPER(TRIM(IFNULL(SP.ASTRAL_TRAVEL,'')))
    ,UPPER(TRIM(IFNULL(SP.AUDIO_CONTROL,'')))
    ,UPPER(TRIM(IFNULL(SP.DEXTERITY,'')))
    ,UPPER(TRIM(IFNULL(SP.OMNITRIX,'')))
    ,UPPER(TRIM(IFNULL(SP.SUPER_SPEED,'')))
    ,UPPER(TRIM(IFNULL(SP.POSSESSION,'')))
    ,UPPER(TRIM(IFNULL(SP.ANIMAL_ORIENTED_POWERS,'')))
    ,UPPER(TRIM(IFNULL(SP.WEAPON_BASED_POWERS,'')))
    ,UPPER(TRIM(IFNULL(SP.ELECTROKINESIS,'')))
    ,UPPER(TRIM(IFNULL(SP.DARKFORCE_MANIPULATION,'')))
    ,UPPER(TRIM(IFNULL(SP.DEATH_TOUCH,'')))
    ,UPPER(TRIM(IFNULL(SP.TELEPORTATION,'')))
    ,UPPER(TRIM(IFNULL(SP.ENHANCED_SENSES,'')))
    ,UPPER(TRIM(IFNULL(SP.TELEKINESIS,'')))
    ,UPPER(TRIM(IFNULL(SP.ENERGY_BEAMS,'')))
    ,UPPER(TRIM(IFNULL(SP.MAGIC,'')))
    ,UPPER(TRIM(IFNULL(SP.HYPERKINESIS,'')))
    ,UPPER(TRIM(IFNULL(SP.JUMP,'')))
    ,UPPER(TRIM(IFNULL(SP.CLAIRVOYANCE,'')))
    ,UPPER(TRIM(IFNULL(SP.DIMENSIONAL_TRAVEL,'')))
    ,UPPER(TRIM(IFNULL(SP.POWER_SENSE,'')))
    ,UPPER(TRIM(IFNULL(SP.SHAPESHIFTING,'')))
    ,UPPER(TRIM(IFNULL(SP.PEAK_HUMAN_CONDITION,'')))
    ,UPPER(TRIM(IFNULL(SP.IMMORTALITY,'')))
    ,UPPER(TRIM(IFNULL(SP.CAMOUFLAGE,'')))
    ,UPPER(TRIM(IFNULL(SP.ELEMENT_CONTROL,'')))
    ,UPPER(TRIM(IFNULL(SP.PHASING,'')))
    ,UPPER(TRIM(IFNULL(SP.ASTRAL_PROJECTION,'')))
    ,UPPER(TRIM(IFNULL(SP.ELECTRICAL_TRANSPORT,'')))
    ,UPPER(TRIM(IFNULL(SP.FIRE_CONTROL,'')))
    ,UPPER(TRIM(IFNULL(SP.PROJECTION,'')))
    ,UPPER(TRIM(IFNULL(SP.SUMMONING,'')))
    ,UPPER(TRIM(IFNULL(SP.ENHANCED_MEMORY,'')))
    ,UPPER(TRIM(IFNULL(SP.REFLEXES,'')))
    ,UPPER(TRIM(IFNULL(SP.INVULNERABILITY,'')))
    ,UPPER(TRIM(IFNULL(SP.ENERGY_CONSTRUCTS,'')))
    ,UPPER(TRIM(IFNULL(SP.FORCE_FIELDS,'')))
    ,UPPER(TRIM(IFNULL(SP.SELF_SUSTENANCE,'')))
    ,UPPER(TRIM(IFNULL(SP.ANTI_GRAVITY,'')))
    ,UPPER(TRIM(IFNULL(SP.EMPATHY,'')))
    ,UPPER(TRIM(IFNULL(SP.POWER_NULLIFIER,'')))
    ,UPPER(TRIM(IFNULL(SP.RADIATION_CONTROL,'')))
    ,UPPER(TRIM(IFNULL(SP.PSIONIC_POWERS,'')))
    ,UPPER(TRIM(IFNULL(SP.ELASTICITY,'')))
    ,UPPER(TRIM(IFNULL(SP.SUBSTANCE_SECRETION,'')))
    ,UPPER(TRIM(IFNULL(SP.ELEMENTAL_TRANSMOGRIFICATION,'')))
    ,UPPER(TRIM(IFNULL(SP.TECHNOPATH_CYBERPATH,'')))
    ,UPPER(TRIM(IFNULL(SP.PHOTOGRAPHIC_REFLEXES,'')))
    ,UPPER(TRIM(IFNULL(SP.SEISMIC_POWER,'')))
    ,UPPER(TRIM(IFNULL(SP.ANIMATION,'')))
    ,UPPER(TRIM(IFNULL(SP.PRECOGNITION,'')))
    ,UPPER(TRIM(IFNULL(SP.MIND_CONTROL,'')))
    ,UPPER(TRIM(IFNULL(SP.FIRE_RESISTANCE,'')))
    ,UPPER(TRIM(IFNULL(SP.POWER_ABSORPTION,'')))
    ,UPPER(TRIM(IFNULL(SP.ENHANCED_HEARING,'')))
    ,UPPER(TRIM(IFNULL(SP.NOVA_FORCE,'')))
    ,UPPER(TRIM(IFNULL(SP.INSANITY,'')))
    ,UPPER(TRIM(IFNULL(SP.HYPNOKINESIS,'')))
    ,UPPER(TRIM(IFNULL(SP.ANIMAL_CONTROL,'')))
    ,UPPER(TRIM(IFNULL(SP.NATURAL_ARMOR,'')))
    ,UPPER(TRIM(IFNULL(SP.INTANGIBILITY,'')))
    ,UPPER(TRIM(IFNULL(SP.ENHANCED_SIGHT,'')))
    ,UPPER(TRIM(IFNULL(SP.MOLECULAR_MANIPULATION,'')))
    ,UPPER(TRIM(IFNULL(SP.HEAT_GENERATION,'')))
    ,UPPER(TRIM(IFNULL(SP.ADAPTATION,'')))
    ,UPPER(TRIM(IFNULL(SP.GLIDING,'')))
    ,UPPER(TRIM(IFNULL(SP.POWER_SUIT,'')))
    ,UPPER(TRIM(IFNULL(SP.MIND_BLAST,'')))
    ,UPPER(TRIM(IFNULL(SP.PROBABILITY_MANIPULATION,'')))
    ,UPPER(TRIM(IFNULL(SP.GRAVITY_CONTROL,'')))
    ,UPPER(TRIM(IFNULL(SP.REGENERATION,'')))
    ,UPPER(TRIM(IFNULL(SP.LIGHT_CONTROL,'')))
    ,UPPER(TRIM(IFNULL(SP.ECHOLOCATION,'')))
    ,UPPER(TRIM(IFNULL(SP.LEVITATION,'')))
    ,UPPER(TRIM(IFNULL(SP.TOXIN_AND_DISEASE_CONTROL,'')))
    ,UPPER(TRIM(IFNULL(SP.BANISH,'')))
    ,UPPER(TRIM(IFNULL(SP.ENERGY_MANIPULATION,'')))
    ,UPPER(TRIM(IFNULL(SP.HEAT_RESISTANCE,'')))
    ,UPPER(TRIM(IFNULL(SP.NATURAL_WEAPONS,'')))
    ,UPPER(TRIM(IFNULL(SP.TIME_TRAVEL,'')))
    ,UPPER(TRIM(IFNULL(SP.ENHANCED_SMELL,'')))
    ,UPPER(TRIM(IFNULL(SP.ILLUSIONS,'')))
    ,UPPER(TRIM(IFNULL(SP.THIRSTOKINESIS,'')))
    ,UPPER(TRIM(IFNULL(SP.HAIR_MANIPULATION,'')))
    ,UPPER(TRIM(IFNULL(SP.ILLUMINATION,'')))
    ,UPPER(TRIM(IFNULL(SP.OMNIPOTENT,'')))
    ,UPPER(TRIM(IFNULL(SP.CLOAKING,'')))
    ,UPPER(TRIM(IFNULL(SP.CHANGING_ARMOR,'')))
    ,UPPER(TRIM(IFNULL(SP.POWER_COSMIC,'')))
    ,UPPER(TRIM(IFNULL(SP.BIOKINESIS,'')))
    ,UPPER(TRIM(IFNULL(SP.WATER_CONTROL,'')))
    ,UPPER(TRIM(IFNULL(SP.RADIATION_IMMUNITY,'')))
    ,UPPER(TRIM(IFNULL(SP.VISION_TELESCOPIC,'')))
    ,UPPER(TRIM(IFNULL(SP.TOXIN_AND_DISEASE_RESISTANCE,'')))
    ,UPPER(TRIM(IFNULL(SP.SPATIAL_AWARENESS,'')))
    ,UPPER(TRIM(IFNULL(SP.ENERGY_RESISTANCE,'')))
    ,UPPER(TRIM(IFNULL(SP.TELEPATHY_RESISTANCE,'')))
    ,UPPER(TRIM(IFNULL(SP.MOLECULAR_COMBUSTION,'')))
    ,UPPER(TRIM(IFNULL(SP.OMNILINGUALISM,'')))
    ,UPPER(TRIM(IFNULL(SP.PORTAL_CREATION,'')))
    ,UPPER(TRIM(IFNULL(SP.MAGNETISM,'')))
    ,UPPER(TRIM(IFNULL(SP.MIND_CONTROL_RESISTANCE,'')))
    ,UPPER(TRIM(IFNULL(SP.PLANT_CONTROL,'')))
    ,UPPER(TRIM(IFNULL(SP.SONAR,'')))
    ,UPPER(TRIM(IFNULL(SP.SONIC_SCREAM,'')))
    ,UPPER(TRIM(IFNULL(SP.TIME_MANIPULATION,'')))
    ,UPPER(TRIM(IFNULL(SP.ENHANCED_TOUCH,'')))
    ,UPPER(TRIM(IFNULL(SP.MAGIC_RESISTANCE,'')))
    ,UPPER(TRIM(IFNULL(SP.INVISIBILITY,'')))
    ,UPPER(TRIM(IFNULL(SP.SUB_MARINER,'')))
    ,UPPER(TRIM(IFNULL(SP.RADIATION_ABSORPTION,'')))
    ,UPPER(TRIM(IFNULL(SP.INTUITIVE_APTITUDE,'')))
    ,UPPER(TRIM(IFNULL(SP.VISION_MICROSCOPIC,'')))
    ,UPPER(TRIM(IFNULL(SP.MELTING,'')))
    ,UPPER(TRIM(IFNULL(SP.WIND_CONTROL,'')))
    ,UPPER(TRIM(IFNULL(SP.SUPER_BREATH,'')))
    ,UPPER(TRIM(IFNULL(SP.WALLCRAWLING,'')))
    ,UPPER(TRIM(IFNULL(SP.VISION_NIGHT,'')))
    ,UPPER(TRIM(IFNULL(SP.VISION_INFRARED,'')))
    ,UPPER(TRIM(IFNULL(SP.GRIM_REAPING,'')))
    ,UPPER(TRIM(IFNULL(SP.MATTER_ABSORPTION,'')))
    ,UPPER(TRIM(IFNULL(SP.THE_FORCE,'')))
    ,UPPER(TRIM(IFNULL(SP.RESURRECTION,'')))
    ,UPPER(TRIM(IFNULL(SP.TERRAKINESIS,'')))
    ,UPPER(TRIM(IFNULL(SP.VISION_HEAT,'')))
    ,UPPER(TRIM(IFNULL(SP.VITAKINESIS,'')))
    ,UPPER(TRIM(IFNULL(SP.RADAR_SENSE,'')))
    ,UPPER(TRIM(IFNULL(SP.QWARDIAN_POWER_RING,'')))
    ,UPPER(TRIM(IFNULL(SP.WEATHER_CONTROL,'')))
    ,UPPER(TRIM(IFNULL(SP.VISION_XRAY,'')))
    ,UPPER(TRIM(IFNULL(SP.VISION_THERMAL,'')))
    ,UPPER(TRIM(IFNULL(SP.WEB_CREATION,'')))
    ,UPPER(TRIM(IFNULL(SP.REALITY_WARPING,'')))
    ,UPPER(TRIM(IFNULL(SP.ODIN_FORCE,'')))
    ,UPPER(TRIM(IFNULL(SP.SYMBIOTE_COSTUME,'')))
    ,UPPER(TRIM(IFNULL(SP.SPEED_FORCE,'')))
    ,UPPER(TRIM(IFNULL(SP.PHOENIX_FORCE,'')))
    ,UPPER(TRIM(IFNULL(SP.MOLECULAR_DISSIPATION,'')))
    ,UPPER(TRIM(IFNULL(SP.VISION_CRYO,'')))
    ,UPPER(TRIM(IFNULL(SP.OMNIPRESENT,'')))
    ,UPPER(TRIM(IFNULL(SP.OMNISCIENT,'')))
           ),'~')) AS RECORD_HASH 
FROM RAW.SUPERHERO.HEROES_INFORMATION HI
LEFT JOIN RAW.SUPERHERO.SUPERHERO_POWERS SP
    ON HI.NAME = SP.HERO_NAMES
;

select * from STG_SUPERHERO_SET;

INSERT INTO superhero.HUB_BEING
SELECT 
    DISTINCT 
    HUB_BEING_KEY,
    BEING_ID,
    BEING_ID_BKCC,
    RECORD_SOURCE,
    LOAD_DATE     
FROM DATA_VAULT.STAGING.STG_SUPERHERO_SET STG
 WHERE NOT EXISTS (SELECT * FROM DATA_VAULT.SUPERHERO.HUB_BEING HB WHERE STG.HUB_BEING_KEY = HB.HUB_BEING_KEY );





INSERT INTO superhero.SAT_BEING_SUPERHERO_SET
SELECT 
    SAT_BEING_SUPERHERO_SET_KEY,
	HUB_BEING_KEY,
    BEING_ID,
    BEING_ID_BKCC,
    NAME,
    GENDER,
    EYE_COLOR,
    RACE,
    HAIR_COLOR,
    HEIGHT,
    WEIGHT,
    SKIN_COLOR,
	PUBLISHER,
	ALIGNMENT,
	AGILITY,
	ACCELERATED_HEALING,
	LANTERN_POWER_RING,
	DIMENSIONAL_AWARENESS,
	COLD_RESISTANCE,
	DURABILITY,
	STEALTH,
	ENERGY_ABSORPTION,
	FLIGHT,
	DANGER_SENSE,
	UNDERWATER_BREATHING,
	MARKSMANSHIP,
	WEAPONS_MASTER,
	POWER_AUGMENTATION,
	ANIMAL_ATTRIBUTES,
	LONGEVITY,
	INTELLIGENCE,
	SUPER_STRENGTH,
	CRYOKINESIS,
	TELEPATHY,
	ENERGY_ARMOR,
	ENERGY_BLASTS,
	DUPLICATION,
	SIZE_CHANGING,
	DENSITY_CONTROL,
	STAMINA,
	ASTRAL_TRAVEL,
	AUDIO_CONTROL,
	DEXTERITY,
	OMNITRIX,
	SUPER_SPEED,
	POSSESSION,
	ANIMAL_ORIENTED_POWERS,
	WEAPON_BASED_POWERS,
	ELECTROKINESIS,
	DARKFORCE_MANIPULATION,
	DEATH_TOUCH,
	TELEPORTATION,
	ENHANCED_SENSES,
	TELEKINESIS,
	ENERGY_BEAMS,
	MAGIC,
	HYPERKINESIS,
	JUMP,
	CLAIRVOYANCE,
	DIMENSIONAL_TRAVEL,
	POWER_SENSE,
	SHAPESHIFTING,
	PEAK_HUMAN_CONDITION,
	IMMORTALITY,
	CAMOUFLAGE,
	ELEMENT_CONTROL,
	PHASING,
	ASTRAL_PROJECTION,
	ELECTRICAL_TRANSPORT,
	FIRE_CONTROL,
	PROJECTION,
	SUMMONING,
	ENHANCED_MEMORY,
	REFLEXES,
	INVULNERABILITY,
	ENERGY_CONSTRUCTS,
	FORCE_FIELDS,
	SELF_SUSTENANCE,
	ANTI_GRAVITY,
	EMPATHY,
	POWER_NULLIFIER,
	RADIATION_CONTROL,
	PSIONIC_POWERS,
	ELASTICITY,
	SUBSTANCE_SECRETION,
	ELEMENTAL_TRANSMOGRIFICATION,
	TECHNOPATH_CYBERPATH,
	PHOTOGRAPHIC_REFLEXES,
	SEISMIC_POWER,
	ANIMATION,
	PRECOGNITION,
	MIND_CONTROL,
	FIRE_RESISTANCE,
	POWER_ABSORPTION,
	ENHANCED_HEARING,
	NOVA_FORCE,
	INSANITY,
	HYPNOKINESIS,
	ANIMAL_CONTROL,
	NATURAL_ARMOR,
	INTANGIBILITY,
	ENHANCED_SIGHT,
	MOLECULAR_MANIPULATION,
	HEAT_GENERATION,
	ADAPTATION,
	GLIDING,
	POWER_SUIT,
	MIND_BLAST,
	PROBABILITY_MANIPULATION,
	GRAVITY_CONTROL,
	REGENERATION,
	LIGHT_CONTROL,
	ECHOLOCATION,
	LEVITATION,
	TOXIN_AND_DISEASE_CONTROL,
	BANISH,
	ENERGY_MANIPULATION,
	HEAT_RESISTANCE,
	NATURAL_WEAPONS,
	TIME_TRAVEL,
	ENHANCED_SMELL,
	ILLUSIONS,
	THIRSTOKINESIS,
	HAIR_MANIPULATION,
	ILLUMINATION,
	OMNIPOTENT,
	CLOAKING,
	CHANGING_ARMOR,
	POWER_COSMIC,
	BIOKINESIS,
	WATER_CONTROL,
	RADIATION_IMMUNITY,
	VISION_TELESCOPIC,
	TOXIN_AND_DISEASE_RESISTANCE,
	SPATIAL_AWARENESS,
	ENERGY_RESISTANCE,
	TELEPATHY_RESISTANCE,
	MOLECULAR_COMBUSTION,
	OMNILINGUALISM,
	PORTAL_CREATION,
	MAGNETISM,
	MIND_CONTROL_RESISTANCE,
	PLANT_CONTROL,
	SONAR,
	SONIC_SCREAM,
	TIME_MANIPULATION,
	ENHANCED_TOUCH,
	MAGIC_RESISTANCE,
	INVISIBILITY,
	SUB_MARINER,
	RADIATION_ABSORPTION,
	INTUITIVE_APTITUDE,
	VISION_MICROSCOPIC,
	MELTING,
	WIND_CONTROL,
	SUPER_BREATH,
	WALLCRAWLING,
	VISION_NIGHT,
	VISION_INFRARED,
	GRIM_REAPING,
	MATTER_ABSORPTION,
	THE_FORCE,
	RESURRECTION,
	TERRAKINESIS,
	VISION_HEAT,
	VITAKINESIS,
	RADAR_SENSE,
	QWARDIAN_POWER_RING,
	WEATHER_CONTROL,
	VISION_XRAY,
	VISION_THERMAL,
	WEB_CREATION,
	REALITY_WARPING,
	ODIN_FORCE,
	SYMBIOTE_COSTUME,
	SPEED_FORCE,
	PHOENIX_FORCE,
	MOLECULAR_DISSIPATION,
	VISION_CRYO,
	OMNIPRESENT,
	OMNISCIENT,
	RECORD_HASH,
    LOAD_DATE
FROM DATA_VAULT.STAGING.STG_SUPERHERO_SET STG
 WHERE NOT EXISTS (SELECT * FROM superhero.SAT_BEING_SUPERHERO_SET HB 
                   WHERE STG.HUB_BEING_KEY = HB.HUB_BEING_KEY
                  AND STG.RECORD_HASH = HB.RECORD_HASH);


SELECT * 
FROM DATA_VAULT.SUPERHERO.HUB_BEING;

SELECT *
FROM DATA_VAULT.SUPERHERO.SAT_BEING_SUPERHERO_SET;

