use database mart;
use schema superhero;
use role sysadmin;

CREATE OR REPLACE VIEW BEINGS_ALL
AS

WITH SUPERHERO_SET_POWERS
AS (
        select *
        from (
        SELECT
        HUB_BEING_KEY,
        IFF (AGILITY, INITCAP('AGILITY'), NULL ) AGILITY, 
IFF (ACCELERATED_HEALING, INITCAP('ACCELERATED_HEALING'), NULL ) ACCELERATED_HEALING, 
IFF (LANTERN_POWER_RING, INITCAP('LANTERN_POWER_RING'), NULL ) LANTERN_POWER_RING, 
IFF (DIMENSIONAL_AWARENESS, INITCAP('DIMENSIONAL_AWARENESS'), NULL ) DIMENSIONAL_AWARENESS, 
IFF (COLD_RESISTANCE, INITCAP('COLD_RESISTANCE'), NULL ) COLD_RESISTANCE, 
IFF (DURABILITY, INITCAP('DURABILITY'), NULL ) DURABILITY, 
IFF (STEALTH, INITCAP('STEALTH'), NULL ) STEALTH, 
IFF (ENERGY_ABSORPTION, INITCAP('ENERGY_ABSORPTION'), NULL ) ENERGY_ABSORPTION, 
IFF (FLIGHT, INITCAP('FLIGHT'), NULL ) FLIGHT, 
IFF (DANGER_SENSE, INITCAP('DANGER_SENSE'), NULL ) DANGER_SENSE, 
IFF (UNDERWATER_BREATHING, INITCAP('UNDERWATER_BREATHING'), NULL ) UNDERWATER_BREATHING, 
IFF (MARKSMANSHIP, INITCAP('MARKSMANSHIP'), NULL ) MARKSMANSHIP, 
IFF (WEAPONS_MASTER, INITCAP('WEAPONS_MASTER'), NULL ) WEAPONS_MASTER, 
IFF (POWER_AUGMENTATION, INITCAP('POWER_AUGMENTATION'), NULL ) POWER_AUGMENTATION, 
IFF (ANIMAL_ATTRIBUTES, INITCAP('ANIMAL_ATTRIBUTES'), NULL ) ANIMAL_ATTRIBUTES, 
IFF (LONGEVITY, INITCAP('LONGEVITY'), NULL ) LONGEVITY, 
IFF (INTELLIGENCE, INITCAP('INTELLIGENCE'), NULL ) INTELLIGENCE, 
IFF (SUPER_STRENGTH, INITCAP('SUPER_STRENGTH'), NULL ) SUPER_STRENGTH, 
IFF (CRYOKINESIS, INITCAP('CRYOKINESIS'), NULL ) CRYOKINESIS, 
IFF (TELEPATHY, INITCAP('TELEPATHY'), NULL ) TELEPATHY, 
IFF (ENERGY_ARMOR, INITCAP('ENERGY_ARMOR'), NULL ) ENERGY_ARMOR, 
IFF (ENERGY_BLASTS, INITCAP('ENERGY_BLASTS'), NULL ) ENERGY_BLASTS, 
IFF (DUPLICATION, INITCAP('DUPLICATION'), NULL ) DUPLICATION, 
IFF (SIZE_CHANGING, INITCAP('SIZE_CHANGING'), NULL ) SIZE_CHANGING, 
IFF (DENSITY_CONTROL, INITCAP('DENSITY_CONTROL'), NULL ) DENSITY_CONTROL, 
IFF (STAMINA, INITCAP('STAMINA'), NULL ) STAMINA, 
IFF (ASTRAL_TRAVEL, INITCAP('ASTRAL_TRAVEL'), NULL ) ASTRAL_TRAVEL, 
IFF (AUDIO_CONTROL, INITCAP('AUDIO_CONTROL'), NULL ) AUDIO_CONTROL, 
IFF (DEXTERITY, INITCAP('DEXTERITY'), NULL ) DEXTERITY, 
IFF (OMNITRIX, INITCAP('OMNITRIX'), NULL ) OMNITRIX, 
IFF (SUPER_SPEED, INITCAP('SUPER_SPEED'), NULL ) SUPER_SPEED, 
IFF (POSSESSION, INITCAP('POSSESSION'), NULL ) POSSESSION, 
IFF (ANIMAL_ORIENTED_POWERS, INITCAP('ANIMAL_ORIENTED_POWERS'), NULL ) ANIMAL_ORIENTED_POWERS, 
IFF (WEAPON_BASED_POWERS, INITCAP('WEAPON_BASED_POWERS'), NULL ) WEAPON_BASED_POWERS, 
IFF (ELECTROKINESIS, INITCAP('ELECTROKINESIS'), NULL ) ELECTROKINESIS, 
IFF (DARKFORCE_MANIPULATION, INITCAP('DARKFORCE_MANIPULATION'), NULL ) DARKFORCE_MANIPULATION, 
IFF (DEATH_TOUCH, INITCAP('DEATH_TOUCH'), NULL ) DEATH_TOUCH, 
IFF (TELEPORTATION, INITCAP('TELEPORTATION'), NULL ) TELEPORTATION, 
IFF (ENHANCED_SENSES, INITCAP('ENHANCED_SENSES'), NULL ) ENHANCED_SENSES, 
IFF (TELEKINESIS, INITCAP('TELEKINESIS'), NULL ) TELEKINESIS, 
IFF (ENERGY_BEAMS, INITCAP('ENERGY_BEAMS'), NULL ) ENERGY_BEAMS, 
IFF (MAGIC, INITCAP('MAGIC'), NULL ) MAGIC, 
IFF (HYPERKINESIS, INITCAP('HYPERKINESIS'), NULL ) HYPERKINESIS, 
IFF (JUMP, INITCAP('JUMP'), NULL ) JUMP, 
IFF (CLAIRVOYANCE, INITCAP('CLAIRVOYANCE'), NULL ) CLAIRVOYANCE, 
IFF (DIMENSIONAL_TRAVEL, INITCAP('DIMENSIONAL_TRAVEL'), NULL ) DIMENSIONAL_TRAVEL, 
IFF (POWER_SENSE, INITCAP('POWER_SENSE'), NULL ) POWER_SENSE, 
IFF (SHAPESHIFTING, INITCAP('SHAPESHIFTING'), NULL ) SHAPESHIFTING, 
IFF (PEAK_HUMAN_CONDITION, INITCAP('PEAK_HUMAN_CONDITION'), NULL ) PEAK_HUMAN_CONDITION, 
IFF (IMMORTALITY, INITCAP('IMMORTALITY'), NULL ) IMMORTALITY, 
IFF (CAMOUFLAGE, INITCAP('CAMOUFLAGE'), NULL ) CAMOUFLAGE, 
IFF (ELEMENT_CONTROL, INITCAP('ELEMENT_CONTROL'), NULL ) ELEMENT_CONTROL, 
IFF (PHASING, INITCAP('PHASING'), NULL ) PHASING, 
IFF (ASTRAL_PROJECTION, INITCAP('ASTRAL_PROJECTION'), NULL ) ASTRAL_PROJECTION, 
IFF (ELECTRICAL_TRANSPORT, INITCAP('ELECTRICAL_TRANSPORT'), NULL ) ELECTRICAL_TRANSPORT, 
IFF (FIRE_CONTROL, INITCAP('FIRE_CONTROL'), NULL ) FIRE_CONTROL, 
IFF (PROJECTION, INITCAP('PROJECTION'), NULL ) PROJECTION, 
IFF (SUMMONING, INITCAP('SUMMONING'), NULL ) SUMMONING, 
IFF (ENHANCED_MEMORY, INITCAP('ENHANCED_MEMORY'), NULL ) ENHANCED_MEMORY, 
IFF (REFLEXES, INITCAP('REFLEXES'), NULL ) REFLEXES, 
IFF (INVULNERABILITY, INITCAP('INVULNERABILITY'), NULL ) INVULNERABILITY, 
IFF (ENERGY_CONSTRUCTS, INITCAP('ENERGY_CONSTRUCTS'), NULL ) ENERGY_CONSTRUCTS, 
IFF (FORCE_FIELDS, INITCAP('FORCE_FIELDS'), NULL ) FORCE_FIELDS, 
IFF (SELF_SUSTENANCE, INITCAP('SELF_SUSTENANCE'), NULL ) SELF_SUSTENANCE, 
IFF (ANTI_GRAVITY, INITCAP('ANTI_GRAVITY'), NULL ) ANTI_GRAVITY, 
IFF (EMPATHY, INITCAP('EMPATHY'), NULL ) EMPATHY, 
IFF (POWER_NULLIFIER, INITCAP('POWER_NULLIFIER'), NULL ) POWER_NULLIFIER, 
IFF (RADIATION_CONTROL, INITCAP('RADIATION_CONTROL'), NULL ) RADIATION_CONTROL, 
IFF (PSIONIC_POWERS, INITCAP('PSIONIC_POWERS'), NULL ) PSIONIC_POWERS, 
IFF (ELASTICITY, INITCAP('ELASTICITY'), NULL ) ELASTICITY, 
IFF (SUBSTANCE_SECRETION, INITCAP('SUBSTANCE_SECRETION'), NULL ) SUBSTANCE_SECRETION, 
IFF (ELEMENTAL_TRANSMOGRIFICATION, INITCAP('ELEMENTAL_TRANSMOGRIFICATION'), NULL ) ELEMENTAL_TRANSMOGRIFICATION, 
IFF (TECHNOPATH_CYBERPATH, INITCAP('TECHNOPATH_CYBERPATH'), NULL ) TECHNOPATH_CYBERPATH, 
IFF (PHOTOGRAPHIC_REFLEXES, INITCAP('PHOTOGRAPHIC_REFLEXES'), NULL ) PHOTOGRAPHIC_REFLEXES, 
IFF (SEISMIC_POWER, INITCAP('SEISMIC_POWER'), NULL ) SEISMIC_POWER, 
IFF (ANIMATION, INITCAP('ANIMATION'), NULL ) ANIMATION, 
IFF (PRECOGNITION, INITCAP('PRECOGNITION'), NULL ) PRECOGNITION, 
IFF (MIND_CONTROL, INITCAP('MIND_CONTROL'), NULL ) MIND_CONTROL, 
IFF (FIRE_RESISTANCE, INITCAP('FIRE_RESISTANCE'), NULL ) FIRE_RESISTANCE, 
IFF (POWER_ABSORPTION, INITCAP('POWER_ABSORPTION'), NULL ) POWER_ABSORPTION, 
IFF (ENHANCED_HEARING, INITCAP('ENHANCED_HEARING'), NULL ) ENHANCED_HEARING, 
IFF (NOVA_FORCE, INITCAP('NOVA_FORCE'), NULL ) NOVA_FORCE, 
IFF (INSANITY, INITCAP('INSANITY'), NULL ) INSANITY, 
IFF (HYPNOKINESIS, INITCAP('HYPNOKINESIS'), NULL ) HYPNOKINESIS, 
IFF (ANIMAL_CONTROL, INITCAP('ANIMAL_CONTROL'), NULL ) ANIMAL_CONTROL, 
IFF (NATURAL_ARMOR, INITCAP('NATURAL_ARMOR'), NULL ) NATURAL_ARMOR, 
IFF (INTANGIBILITY, INITCAP('INTANGIBILITY'), NULL ) INTANGIBILITY, 
IFF (ENHANCED_SIGHT, INITCAP('ENHANCED_SIGHT'), NULL ) ENHANCED_SIGHT, 
IFF (MOLECULAR_MANIPULATION, INITCAP('MOLECULAR_MANIPULATION'), NULL ) MOLECULAR_MANIPULATION, 
IFF (HEAT_GENERATION, INITCAP('HEAT_GENERATION'), NULL ) HEAT_GENERATION, 
IFF (ADAPTATION, INITCAP('ADAPTATION'), NULL ) ADAPTATION, 
IFF (GLIDING, INITCAP('GLIDING'), NULL ) GLIDING, 
IFF (POWER_SUIT, INITCAP('POWER_SUIT'), NULL ) POWER_SUIT, 
IFF (MIND_BLAST, INITCAP('MIND_BLAST'), NULL ) MIND_BLAST, 
IFF (PROBABILITY_MANIPULATION, INITCAP('PROBABILITY_MANIPULATION'), NULL ) PROBABILITY_MANIPULATION, 
IFF (GRAVITY_CONTROL, INITCAP('GRAVITY_CONTROL'), NULL ) GRAVITY_CONTROL, 
IFF (REGENERATION, INITCAP('REGENERATION'), NULL ) REGENERATION, 
IFF (LIGHT_CONTROL, INITCAP('LIGHT_CONTROL'), NULL ) LIGHT_CONTROL, 
IFF (ECHOLOCATION, INITCAP('ECHOLOCATION'), NULL ) ECHOLOCATION, 
IFF (LEVITATION, INITCAP('LEVITATION'), NULL ) LEVITATION, 
IFF (TOXIN_AND_DISEASE_CONTROL, INITCAP('TOXIN_AND_DISEASE_CONTROL'), NULL ) TOXIN_AND_DISEASE_CONTROL, 
IFF (BANISH, INITCAP('BANISH'), NULL ) BANISH, 
IFF (ENERGY_MANIPULATION, INITCAP('ENERGY_MANIPULATION'), NULL ) ENERGY_MANIPULATION, 
IFF (HEAT_RESISTANCE, INITCAP('HEAT_RESISTANCE'), NULL ) HEAT_RESISTANCE, 
IFF (NATURAL_WEAPONS, INITCAP('NATURAL_WEAPONS'), NULL ) NATURAL_WEAPONS, 
IFF (TIME_TRAVEL, INITCAP('TIME_TRAVEL'), NULL ) TIME_TRAVEL, 
IFF (ENHANCED_SMELL, INITCAP('ENHANCED_SMELL'), NULL ) ENHANCED_SMELL, 
IFF (ILLUSIONS, INITCAP('ILLUSIONS'), NULL ) ILLUSIONS, 
IFF (THIRSTOKINESIS, INITCAP('THIRSTOKINESIS'), NULL ) THIRSTOKINESIS, 
IFF (HAIR_MANIPULATION, INITCAP('HAIR_MANIPULATION'), NULL ) HAIR_MANIPULATION, 
IFF (ILLUMINATION, INITCAP('ILLUMINATION'), NULL ) ILLUMINATION, 
IFF (OMNIPOTENT, INITCAP('OMNIPOTENT'), NULL ) OMNIPOTENT, 
IFF (CLOAKING, INITCAP('CLOAKING'), NULL ) CLOAKING, 
IFF (CHANGING_ARMOR, INITCAP('CHANGING_ARMOR'), NULL ) CHANGING_ARMOR, 
IFF (POWER_COSMIC, INITCAP('POWER_COSMIC'), NULL ) POWER_COSMIC, 
IFF (BIOKINESIS, INITCAP('BIOKINESIS'), NULL ) BIOKINESIS, 
IFF (WATER_CONTROL, INITCAP('WATER_CONTROL'), NULL ) WATER_CONTROL, 
IFF (RADIATION_IMMUNITY, INITCAP('RADIATION_IMMUNITY'), NULL ) RADIATION_IMMUNITY, 
IFF (VISION_TELESCOPIC, INITCAP('VISION_TELESCOPIC'), NULL ) VISION_TELESCOPIC, 
IFF (TOXIN_AND_DISEASE_RESISTANCE, INITCAP('TOXIN_AND_DISEASE_RESISTANCE'), NULL ) TOXIN_AND_DISEASE_RESISTANCE, 
IFF (SPATIAL_AWARENESS, INITCAP('SPATIAL_AWARENESS'), NULL ) SPATIAL_AWARENESS, 
IFF (ENERGY_RESISTANCE, INITCAP('ENERGY_RESISTANCE'), NULL ) ENERGY_RESISTANCE, 
IFF (TELEPATHY_RESISTANCE, INITCAP('TELEPATHY_RESISTANCE'), NULL ) TELEPATHY_RESISTANCE, 
IFF (MOLECULAR_COMBUSTION, INITCAP('MOLECULAR_COMBUSTION'), NULL ) MOLECULAR_COMBUSTION, 
IFF (OMNILINGUALISM, INITCAP('OMNILINGUALISM'), NULL ) OMNILINGUALISM, 
IFF (PORTAL_CREATION, INITCAP('PORTAL_CREATION'), NULL ) PORTAL_CREATION, 
IFF (MAGNETISM, INITCAP('MAGNETISM'), NULL ) MAGNETISM, 
IFF (MIND_CONTROL_RESISTANCE, INITCAP('MIND_CONTROL_RESISTANCE'), NULL ) MIND_CONTROL_RESISTANCE, 
IFF (PLANT_CONTROL, INITCAP('PLANT_CONTROL'), NULL ) PLANT_CONTROL, 
IFF (SONAR, INITCAP('SONAR'), NULL ) SONAR, 
IFF (SONIC_SCREAM, INITCAP('SONIC_SCREAM'), NULL ) SONIC_SCREAM, 
IFF (TIME_MANIPULATION, INITCAP('TIME_MANIPULATION'), NULL ) TIME_MANIPULATION, 
IFF (ENHANCED_TOUCH, INITCAP('ENHANCED_TOUCH'), NULL ) ENHANCED_TOUCH, 
IFF (MAGIC_RESISTANCE, INITCAP('MAGIC_RESISTANCE'), NULL ) MAGIC_RESISTANCE, 
IFF (INVISIBILITY, INITCAP('INVISIBILITY'), NULL ) INVISIBILITY, 
IFF (SUB_MARINER, INITCAP('SUB_MARINER'), NULL ) SUB_MARINER, 
IFF (RADIATION_ABSORPTION, INITCAP('RADIATION_ABSORPTION'), NULL ) RADIATION_ABSORPTION, 
IFF (INTUITIVE_APTITUDE, INITCAP('INTUITIVE_APTITUDE'), NULL ) INTUITIVE_APTITUDE, 
IFF (VISION_MICROSCOPIC, INITCAP('VISION_MICROSCOPIC'), NULL ) VISION_MICROSCOPIC, 
IFF (MELTING, INITCAP('MELTING'), NULL ) MELTING, 
IFF (WIND_CONTROL, INITCAP('WIND_CONTROL'), NULL ) WIND_CONTROL, 
IFF (SUPER_BREATH, INITCAP('SUPER_BREATH'), NULL ) SUPER_BREATH, 
IFF (WALLCRAWLING, INITCAP('WALLCRAWLING'), NULL ) WALLCRAWLING, 
IFF (VISION_NIGHT, INITCAP('VISION_NIGHT'), NULL ) VISION_NIGHT, 
IFF (VISION_INFRARED, INITCAP('VISION_INFRARED'), NULL ) VISION_INFRARED, 
IFF (GRIM_REAPING, INITCAP('GRIM_REAPING'), NULL ) GRIM_REAPING, 
IFF (MATTER_ABSORPTION, INITCAP('MATTER_ABSORPTION'), NULL ) MATTER_ABSORPTION, 
IFF (THE_FORCE, INITCAP('THE_FORCE'), NULL ) THE_FORCE, 
IFF (RESURRECTION, INITCAP('RESURRECTION'), NULL ) RESURRECTION, 
IFF (TERRAKINESIS, INITCAP('TERRAKINESIS'), NULL ) TERRAKINESIS, 
IFF (VISION_HEAT, INITCAP('VISION_HEAT'), NULL ) VISION_HEAT, 
IFF (VITAKINESIS, INITCAP('VITAKINESIS'), NULL ) VITAKINESIS, 
IFF (RADAR_SENSE, INITCAP('RADAR_SENSE'), NULL ) RADAR_SENSE, 
IFF (QWARDIAN_POWER_RING, INITCAP('QWARDIAN_POWER_RING'), NULL ) QWARDIAN_POWER_RING, 
IFF (WEATHER_CONTROL, INITCAP('WEATHER_CONTROL'), NULL ) WEATHER_CONTROL, 
IFF (VISION_XRAY, INITCAP('VISION_XRAY'), NULL ) VISION_XRAY, 
IFF (VISION_THERMAL, INITCAP('VISION_THERMAL'), NULL ) VISION_THERMAL, 
IFF (WEB_CREATION, INITCAP('WEB_CREATION'), NULL ) WEB_CREATION, 
IFF (REALITY_WARPING, INITCAP('REALITY_WARPING'), NULL ) REALITY_WARPING, 
IFF (ODIN_FORCE, INITCAP('ODIN_FORCE'), NULL ) ODIN_FORCE, 
IFF (SYMBIOTE_COSTUME, INITCAP('SYMBIOTE_COSTUME'), NULL ) SYMBIOTE_COSTUME, 
IFF (SPEED_FORCE, INITCAP('SPEED_FORCE'), NULL ) SPEED_FORCE, 
IFF (PHOENIX_FORCE, INITCAP('PHOENIX_FORCE'), NULL ) PHOENIX_FORCE, 
IFF (MOLECULAR_DISSIPATION, INITCAP('MOLECULAR_DISSIPATION'), NULL ) MOLECULAR_DISSIPATION, 
IFF (VISION_CRYO, INITCAP('VISION_CRYO'), NULL ) VISION_CRYO, 
IFF (OMNIPRESENT, INITCAP('OMNIPRESENT'), NULL ) OMNIPRESENT, 
IFF (OMNISCIENT, INITCAP('OMNISCIENT'), NULL ) OMNISCIENT
            from DATA_VAULT.SUPERHERO.SAT_BEING_SUPERHERO_SET
            )
        unpivot (col_val for POWERS in (AGILITY, ACCELERATED_HEALING, LANTERN_POWER_RING, DIMENSIONAL_AWARENESS, COLD_RESISTANCE, DURABILITY, STEALTH, ENERGY_ABSORPTION, FLIGHT, DANGER_SENSE, UNDERWATER_BREATHING, MARKSMANSHIP, WEAPONS_MASTER, POWER_AUGMENTATION, ANIMAL_ATTRIBUTES, LONGEVITY, INTELLIGENCE, SUPER_STRENGTH, CRYOKINESIS, TELEPATHY, ENERGY_ARMOR, ENERGY_BLASTS, DUPLICATION, SIZE_CHANGING, DENSITY_CONTROL, STAMINA, ASTRAL_TRAVEL, AUDIO_CONTROL, DEXTERITY, OMNITRIX, SUPER_SPEED, POSSESSION, ANIMAL_ORIENTED_POWERS, WEAPON_BASED_POWERS, ELECTROKINESIS, DARKFORCE_MANIPULATION, DEATH_TOUCH, TELEPORTATION, ENHANCED_SENSES, TELEKINESIS, ENERGY_BEAMS, MAGIC, HYPERKINESIS, JUMP, CLAIRVOYANCE, DIMENSIONAL_TRAVEL, POWER_SENSE, SHAPESHIFTING, PEAK_HUMAN_CONDITION, IMMORTALITY, CAMOUFLAGE, ELEMENT_CONTROL, PHASING, ASTRAL_PROJECTION, ELECTRICAL_TRANSPORT, FIRE_CONTROL, PROJECTION, SUMMONING, ENHANCED_MEMORY, REFLEXES, INVULNERABILITY, ENERGY_CONSTRUCTS, FORCE_FIELDS, SELF_SUSTENANCE, ANTI_GRAVITY, EMPATHY, POWER_NULLIFIER, RADIATION_CONTROL, PSIONIC_POWERS, ELASTICITY, SUBSTANCE_SECRETION, ELEMENTAL_TRANSMOGRIFICATION, TECHNOPATH_CYBERPATH, PHOTOGRAPHIC_REFLEXES, SEISMIC_POWER, ANIMATION, PRECOGNITION, MIND_CONTROL, FIRE_RESISTANCE, POWER_ABSORPTION, ENHANCED_HEARING, NOVA_FORCE, INSANITY, HYPNOKINESIS, ANIMAL_CONTROL, NATURAL_ARMOR, INTANGIBILITY, ENHANCED_SIGHT, MOLECULAR_MANIPULATION, HEAT_GENERATION, ADAPTATION, GLIDING, POWER_SUIT, MIND_BLAST, PROBABILITY_MANIPULATION, GRAVITY_CONTROL, REGENERATION, LIGHT_CONTROL, ECHOLOCATION, LEVITATION, TOXIN_AND_DISEASE_CONTROL, BANISH, ENERGY_MANIPULATION, HEAT_RESISTANCE, NATURAL_WEAPONS, TIME_TRAVEL, ENHANCED_SMELL, ILLUSIONS, THIRSTOKINESIS, HAIR_MANIPULATION, ILLUMINATION, OMNIPOTENT, CLOAKING, CHANGING_ARMOR, POWER_COSMIC, BIOKINESIS, WATER_CONTROL, RADIATION_IMMUNITY, VISION_TELESCOPIC, TOXIN_AND_DISEASE_RESISTANCE, SPATIAL_AWARENESS, ENERGY_RESISTANCE, TELEPATHY_RESISTANCE, MOLECULAR_COMBUSTION, OMNILINGUALISM, PORTAL_CREATION, MAGNETISM, MIND_CONTROL_RESISTANCE, PLANT_CONTROL, SONAR, SONIC_SCREAM, TIME_MANIPULATION, ENHANCED_TOUCH, MAGIC_RESISTANCE, INVISIBILITY, SUB_MARINER, RADIATION_ABSORPTION, INTUITIVE_APTITUDE, VISION_MICROSCOPIC, MELTING, WIND_CONTROL, SUPER_BREATH, WALLCRAWLING, VISION_NIGHT, VISION_INFRARED, GRIM_REAPING, MATTER_ABSORPTION, THE_FORCE, RESURRECTION, TERRAKINESIS, VISION_HEAT, VITAKINESIS, RADAR_SENSE, QWARDIAN_POWER_RING, WEATHER_CONTROL, VISION_XRAY, VISION_THERMAL, WEB_CREATION, REALITY_WARPING, ODIN_FORCE, SYMBIOTE_COSTUME, SPEED_FORCE, PHOENIX_FORCE, MOLECULAR_DISSIPATION, VISION_CRYO, OMNIPRESENT, OMNISCIENT))
            )

SELECT 
RECORD_SOURCE:Source_System::string AS DATA_SOURCE
,HB.BEING_ID
,NAME
-- ,ARRAY_TO_STRING(JSON_RAW:aliases::array,',') as ALIASES
,ARRAY_TO_STRING(JSON_RAW:species::array,',') as SPECIES
-- ,ARRAY_TO_STRING(JSON_RAW:secretIdentities::array,',') AS IDENTITIES 
,'Marvel Comics' AS PUBLISHER
,NULL AS ALIGNMENT
,ARRAY_TO_STRING(JSON_RAW:powers::array,',') AS POWERS
 FROM DATA_VAULT.SUPERHERO.HUB_BEING HB
    JOIN DATA_VAULT.SUPERHERO.SAT_BEING_MARVEL_SEARCH BMS
        ON HB.HUB_BEING_KEY = BMS.HUB_BEING_KEY
 WHERE BMS.IS_CURRENT
UNION ALL

SELECT 
RECORD_SOURCE:Source_System::string AS DATA_SOURCE
,HB.BEING_ID
,BSS.NAME
,BSS.RACE
,BSS.PUBLISHER
,BSS.ALIGNMENT
,listagg(COL_VAL, ', ') WITHIN group (order by COL_VAL) AS POWERS
FROM DATA_VAULT.SUPERHERO.HUB_BEING HB
    JOIN DATA_VAULT.SUPERHERO.SAT_BEING_SUPERHERO_SET BSS
        ON HB.HUB_BEING_KEY = BSS.HUB_BEING_KEY
    JOIN SUPERHERO_SET_POWERS SSP
        ON HB.HUB_BEING_KEY = SSP.HUB_BEING_KEY
GROUP BY 1,2,3,4,5,6
;


-- HELPER QRY TO GENERATE SELECT
/*
select 'IFF (' || column_name ||', INITCAP('''||COLUMN_NAME||'''), NULL ) ' || COLUMN_NAME||', '
column_name from 
data_vault.information_schema.columns
where table_name = 'SAT_BEING_SUPERHERO_SET'
and ordinal_position between 14 and 181
order by ordinal_position;

select listagg(COLUMN_NAME,', ')  within group (order by ORDINAL_POSITION)
column_name from 
data_vault.information_schema.columns
where table_name = 'SAT_BEING_SUPERHERO_SET'
and ordinal_position between 14 and 181
order by ordinal_position;
*/